import re
import json
from datetime import datetime
from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session
from models.auth_models import ActionItem
from utils.logger import logger


ACTION_VERBS = [
    "interview", "test", "build", "conduct", "create", "launch", "calculate",
    "validate", "define", "contact", "deploy", "design", "identify", "prepare",
    "develop", "reach out", "survey", "measure", "secure", "draft"
]


def is_actionable_recommendation(text: str) -> bool:
    """Filters out vague or non-actionable descriptive statements."""
    if not text or len(text.strip()) < 10:
        return False
    lower_text = text.lower().strip()
    return any(verb in lower_text for verb in ACTION_VERBS)


def normalize_title(title: str) -> set:
    """Converts title to a set of normalized lower-case words for similarity check."""
    cleaned = re.sub(r"[^\w\s]", "", title.lower())
    words = set()
    for w in cleaned.split():
        if w.isdigit():
            words.add(w)
        elif len(w) >= 3:
            # Simple stemming: strip trailing 's'
            stemmed = w[:-1] if w.endswith("s") and not w.endswith("ss") else w
            words.add(stemmed)
    return words


def is_duplicate_task(new_title: str, existing_items: List[ActionItem]) -> bool:
    """Performs word-set similarity check to prevent duplicate task creation."""
    new_words = normalize_title(new_title)
    if not new_words:
        return False

    for item in existing_items:
        exist_words = normalize_title(item.title)
        if not exist_words:
            continue

        intersection = new_words.intersection(exist_words)
        union = new_words.union(exist_words)
        similarity = len(intersection) / len(union) if union else 0.0

        if similarity >= 0.65:
            return True

    return False


def determine_priority(source_agent: str, text: str, confidence_score: float) -> str:
    """Derives task priority (CRITICAL, HIGH, MEDIUM, LOW) from context."""
    lower_text = text.lower()
    if any(k in lower_text for k in ["critical", "legal", "compliance", "security", "urgent"]):
        return "CRITICAL"
    if source_agent in ["IdeaAgent", "ProductAgent", "OperationsAgent"] or confidence_score < 70:
        return "HIGH"
    if confidence_score > 90:
        return "MEDIUM"
    return "HIGH"


def extract_and_persist_action_items(
    db: Session,
    user_id: int,
    analysis_id: Optional[int],
    state: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
    Centralized extraction engine. Converts actionable agent recommendations
    into persisted, deduplicated DB ActionItem records.
    """
    existing_db_items = db.query(ActionItem).filter(ActionItem.user_id == user_id).all()
    created_items = []

    agent_mapping = [
        ("idea_analysis", "IdeaAgent", "VALIDATION"),
        ("market_analysis", "MarketAgent", "MARKET"),
        ("business_analysis", "BusinessAgent", "BUSINESS"),
        ("product_analysis", "ProductAgent", "PRODUCT"),
        ("operations_analysis", "OperationsAgent", "OPERATIONS"),
        ("growth_analysis", "GrowthAgent", "GROWTH"),
        ("mentor_analysis", "MentorAgent", "STRATEGY")
    ]

    for state_key, agent_name, category in agent_mapping:
        agent_data = state.get(state_key, {})
        if not isinstance(agent_data, dict) or not agent_data.get("success", True):
            continue

        recs = agent_data.get("recommendations", [])
        conf_metadata = agent_data.get("confidence_metadata", {})
        conf_score = agent_data.get("confidence", 85.0)
        verif_status = conf_metadata.get("verification_status", "SUPPORTED")
        sources_list = agent_data.get("sources", [])

        for rec in recs:
            if not isinstance(rec, str) or not is_actionable_recommendation(rec):
                continue

            clean_title = rec.strip()
            if is_duplicate_task(clean_title, existing_db_items):
                continue

            priority = determine_priority(agent_name, clean_title, conf_score)

            db_item = ActionItem(
                user_id=user_id,
                analysis_id=analysis_id,
                title=clean_title,
                description=f"Generated by {agent_name} during startup analysis.",
                category=category,
                priority=priority,
                reason=rec,
                status="TODO",
                source_agent=agent_name,
                confidence_score=conf_score,
                verification_status=verif_status,
                source_references=json.dumps(sources_list)
            )

            db.add(db_item)
            existing_db_items.append(db_item)
            created_items.append(db_item)

    try:
        db.commit()
        for item in created_items:
            db.refresh(item)
        logger.info(f"Persisted {len(created_items)} new action items for user {user_id}.")
    except Exception as e:
        logger.error(f"Failed to persist action items: {e}")
        db.rollback()

    return [
        {
            "id": it.id,
            "title": it.title,
            "description": it.description,
            "category": it.category,
            "priority": it.priority,
            "status": it.status,
            "source_agent": it.source_agent,
            "confidence_score": it.confidence_score,
            "verification_status": it.verification_status,
            "source_references": json.loads(it.source_references or "[]")
        }
        for it in created_items
    ]
