import React, { useState } from 'react';
import { Download, FileText, FileSpreadsheet, FileCode, Check } from 'lucide-react';
import { useApp } from '../context/AppContext';

export default function ExportCenter() {
  const { analysis } = useApp();
  const [downloadedFormat, setDownloadedFormat] = useState(null);

  const handleExport = (format) => {
    setDownloadedFormat(format);
    const dataStr = JSON.stringify(analysis || {}, null, 2);
    
    let mimeType = 'application/json';
    let fileName = `startup-analysis.${format}`;
    let content = dataStr;

    if (format === 'md') {
      mimeType = 'text/markdown';
      content = `# Startup Analysis Summary\n\nGenerated by IdeaExecutor AI Operating System\n\n\`\`\`json\n${dataStr}\n\`\`\``;
    } else if (format === 'txt') {
      mimeType = 'text/plain';
      content = `Startup Analysis Summary\n\n${dataStr}`;
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setTimeout(() => setDownloadedFormat(null), 2000);
  };

  return (
    <div className="bg-white rounded-3xl p-6 border border-slate-100 shadow-sm text-left">
      <div className="flex items-center gap-2 mb-4 pb-3 border-b border-slate-100">
        <span className="p-2 bg-indigo-50 text-indigo-600 rounded-xl">
          <Download className="w-4 h-4" />
        </span>
        <div>
          <h3 className="text-sm font-extrabold text-slate-800">Export Center</h3>
          <p className="text-[10px] text-slate-400 font-bold">Download your complete startup suite in multiple formats</p>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <button 
          onClick={() => handleExport('json')}
          className="p-3.5 rounded-2xl border border-slate-100 bg-slate-50/60 hover:bg-indigo-50/50 hover:border-indigo-200 transition-all flex flex-col items-center gap-2 group"
        >
          <FileCode className="w-5 h-5 text-indigo-600 group-hover:scale-110 transition-transform" />
          <span className="text-xs font-extrabold text-slate-700">
            {downloadedFormat === 'json' ? 'Downloaded!' : 'JSON Data'}
          </span>
        </button>

        <button 
          onClick={() => handleExport('md')}
          className="p-3.5 rounded-2xl border border-slate-100 bg-slate-50/60 hover:bg-purple-50/50 hover:border-purple-200 transition-all flex flex-col items-center gap-2 group"
        >
          <FileText className="w-5 h-5 text-purple-600 group-hover:scale-110 transition-transform" />
          <span className="text-xs font-extrabold text-slate-700">
            {downloadedFormat === 'md' ? 'Downloaded!' : 'Markdown'}
          </span>
        </button>

        <button 
          onClick={() => handleExport('txt')}
          className="p-3.5 rounded-2xl border border-slate-100 bg-slate-50/60 hover:bg-emerald-50/50 hover:border-emerald-200 transition-all flex flex-col items-center gap-2 group"
        >
          <FileSpreadsheet className="w-5 h-5 text-emerald-600 group-hover:scale-110 transition-transform" />
          <span className="text-xs font-extrabold text-slate-700">
            {downloadedFormat === 'txt' ? 'Downloaded!' : 'Plain Text'}
          </span>
        </button>

        <button 
          onClick={() => window.print()}
          className="p-3.5 rounded-2xl border border-slate-100 bg-slate-50/60 hover:bg-amber-50/50 hover:border-amber-200 transition-all flex flex-col items-center gap-2 group"
        >
          <Download className="w-5 h-5 text-amber-600 group-hover:scale-110 transition-transform" />
          <span className="text-xs font-extrabold text-slate-700">PDF / Print</span>
        </button>
      </div>
    </div>
  );
}
