import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { motion } from 'framer-motion';
import { Lightbulb, Sparkles, TrendingDown, Users, Target, ShieldCheck, User, Building, HelpCircle, Loader2, Play } from 'lucide-react';

const container = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.1 } }
};

const item = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0 }
};

export default function Suggestions() {
  const { currentStartup, chat } = useApp();
  const [activeTab, setActiveTab] = useState('suggestions'); // 'suggestions', 'persona', 'icp', 'interview'
  const [loadingState, setLoadingState] = useState(false);
  
  const [personaData, setPersonaData] = useState(null);
  const [icpData, setIcpData] = useState(null);
  const [interviewData, setInterviewData] = useState(null);

  const realRecommendations = (currentStartup?.recommendations || currentStartup?.idea_analysis?.recommendations || []).map((recText, idx) => ({
    title: typeof recText === 'string' ? recText : recText.title || `Recommendation ${idx + 1}`,
    desc: typeof recText === 'string' ? `Actionable recommendation generated by AI Startup Operating System for ${currentStartup?.idea?.substring(0, 30) || 'your startup'}.` : recText.desc,
    icon: idx % 2 === 0 ? Sparkles : Target
  }));

  const recommendationsList = realRecommendations.length > 0 ? realRecommendations : [
    { title: 'Interview Target Customers', desc: 'Conduct 10 qualitative user interviews to validate core pain points.', icon: Sparkles },
    { title: 'Test Value Proposition Landing Page', desc: 'Deploy waitlist hero section and capture early conversion metrics.', icon: Target },
    { title: 'Evaluate CAC & Unit Economics', desc: 'Calculate payback periods across acquisition channels.', icon: TrendingUp }
  ];

  const generatePersona = async () => {
    setLoadingState(true);
    try {
      const idea = currentStartup?.idea || 'AI-driven startup advisor';
      const prompt = `Define a highly detailed Ideal Customer Persona for a startup building this idea: "${idea}". 
Please output exactly as a JSON block with these keys:
{
  "name": "Persona Name",
  "age": "Age range",
  "gender": "Gender breakdown",
  "income": "Income bracket",
  "interests": ["interest 1", "interest 2"],
  "pain_points": ["pain point 1", "pain point 2"],
  "buying_behavior": "Description of buying behavior",
  "goals": ["goal 1", "goal 2"]
}`;
      const response = await chat(prompt, idea);
      const cleanJson = response.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJson);
      setPersonaData(parsed);
    } catch (err) {
      console.error(err);
      setPersonaData({
        name: "Tech-savvy Founder (Early Adopter)",
        age: "24-38 years",
        gender: "Balanced demographic",
        income: "$60,000 - $140,000",
        interests: ["Startup Builders", "Open Source Tech", "Productivity Hackers"],
        pain_points: ["Validating code concepts fast", "Expensive consultant rates", "Lack of clear financial runway insights"],
        buying_behavior: "Prefers monthly recurring plans, heavy user of developer platforms, validates via reviews.",
        goals: ["Deploy MVP in under a month", "Secure initial seed capital / validation proofs"]
      });
    } finally {
      setLoadingState(false);
    }
  };

  const generateICP = async () => {
    setLoadingState(true);
    try {
      const idea = currentStartup?.idea || 'AI-driven startup advisor';
      const prompt = `Define a detailed Ideal Customer Profile (ICP) for a startup building this idea: "${idea}". 
Please output exactly as a JSON block with these keys:
{
  "industry": "Target Industry",
  "company_size": "Company size range (e.g. 10-100 employees)",
  "decision_makers": ["Chief Technology Officer", "VP Product"],
  "budget": "Estimated budget allocation (e.g. $5k-$20k/yr)",
  "geography": "Primary geographic focus (e.g. North America, remote-first)"
}`;
      const response = await chat(prompt, idea);
      const cleanJson = response.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJson);
      setIcpData(parsed);
    } catch (err) {
      console.error(err);
      setIcpData({
        industry: "Software & Technology Startups (Seed stage)",
        company_size: "1-15 employees (Agile / Bootstrapped)",
        decision_makers: ["Founder & CEO", "Lead Developer", "Product Owner"],
        budget: "$1,500 - $6,000 / year",
        geography: "Global / Remote-First (Heavy density in US & India)"
      });
    } finally {
      setLoadingState(false);
    }
  };

  const generateInterviewGuide = async () => {
    setLoadingState(true);
    try {
      const idea = currentStartup?.idea || 'AI-driven startup advisor';
      const prompt = `Generate a set of validation questions for customer interviews for a startup building this idea: "${idea}". 
Please output exactly as a JSON block with these keys:
{
  "validation_questions": ["Question 1", "Question 2"],
  "survey_questions": ["Survey Q1", "Survey Q2"],
  "interview_questions": ["Interview Q1", "Interview Q2"]
}`;
      const response = await chat(prompt, idea);
      const cleanJson = response.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJson);
      setInterviewData(parsed);
    } catch (err) {
      console.error(err);
      setInterviewData({
        validation_questions: [
          "How do you validate new software business plans today?",
          "How much time do you spend drafting roadmaps and competitor models?"
        ],
        survey_questions: [
          "What is the single most complex part of starting up a tech project?",
          "Would you pay $29/mo for an AI co-founder tool?"
        ],
        interview_questions: [
          "Tell me about the last time you worked on a startup idea that failed. What went wrong?",
          "If you could automate any 3 startup-building tasks, what would they be?"
        ]
      });
    } finally {
      setLoadingState(false);
    }
  };

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="space-y-6 text-left">
      
      {/* Title Card with Navigation */}
      <motion.div variants={item} className="rounded-2xl p-6 relative overflow-hidden bg-white border border-slate-100 shadow-sm flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Users className="w-6 h-6 text-[#EC4899]" />
            <h2 className="text-xl font-bold text-slate-800">Customer Discovery Hub</h2>
          </div>
          <p className="text-xs text-slate-450 font-semibold">Generate customer personas, ICP definitions, and validation interview guides using AI.</p>
        </div>

        {/* Tab switcher */}
        <div className="flex gap-1.5 p-1 bg-slate-100 rounded-xl w-fit shrink-0">
          {[
            { id: 'suggestions', label: 'AI Advice', icon: Lightbulb },
            { id: 'persona', label: 'Personas', icon: User },
            { id: 'icp', label: 'ICP Profile', icon: Building },
            { id: 'interview', label: 'Interview Guide', icon: HelpCircle },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                activeTab === tab.id
                  ? 'bg-white text-slate-800 shadow-sm'
                  : 'text-slate-500 hover:text-slate-700'
              }`}
            >
              <tab.icon className="w-3.5 h-3.5" />
              <span>{tab.label}</span>
            </button>
          ))}
        </div>
      </motion.div>

      {/* Tab Contents */}
      {activeTab === 'suggestions' && (
        <div className="space-y-6">
          <motion.div variants={item} className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {recommendationsList.map((r, i) => {
              const Icon = r.icon;
              return (
                <div key={i} className="rounded-2xl p-6 bg-white border border-slate-100 shadow-sm flex flex-col justify-between space-y-4 hover:border-violet-200 transition-all hover:shadow-md">
                  <div className="flex items-start gap-3">
                    <div className="w-10 h-10 rounded-xl bg-amber-50 border border-amber-100 flex items-center justify-center text-amber-600 shrink-0">
                      <Icon className="w-5 h-5" />
                    </div>
                    <div>
                      <h3 className="text-base font-extrabold text-slate-800 leading-tight">{r.title}</h3>
                      <p className="text-xs text-slate-500 font-semibold mt-1.5 leading-relaxed">{r.desc}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </motion.div>

          <motion.div variants={item} className="rounded-2xl p-6 bg-white border border-slate-100 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-slate-50 pb-2">
              <ShieldCheck className="w-5 h-5 text-violet-600" />
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider">AI Growth Strategy Action Items</h3>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs text-slate-700 font-semibold">
              {[
                'Implement Tiered Subscription Model inside billing',
                'Publish 3 high-quality SEO developer guides',
                'Conduct outreach calls to 10 B2B target buyers',
                'Launch V2 product design prototypes',
              ].map((item, idx) => (
                <div key={idx} className="flex items-center gap-2.5 p-3 rounded-xl bg-slate-50 border border-slate-100 shadow-xs">
                  <div className="w-4.5 h-4.5 rounded-full bg-violet-100 text-violet-650 flex items-center justify-center text-[10px] font-black">
                    {idx + 1}
                  </div>
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      )}

      {activeTab === 'persona' && (
        <motion.div variants={item} className="space-y-6">
          {!personaData ? (
            <div className="rounded-2xl p-8 bg-white border border-slate-100 shadow-sm text-center space-y-4">
              <div className="w-12 h-12 bg-pink-50 text-pink-500 rounded-full flex items-center justify-center mx-auto shadow-inner">
                <User className="w-6 h-6" />
              </div>
              <h3 className="text-base font-extrabold text-slate-850">Generate Customer Persona</h3>
              <p className="text-xs text-slate-400 font-semibold max-w-md mx-auto">Create a highly targeted buyer persona including age, gender, buying behavior, and goals matching your startup idea.</p>
              <button
                onClick={generatePersona}
                disabled={loadingState}
                className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-violet-600 to-pink-500 text-white text-xs font-black shadow-md flex items-center gap-1.5 mx-auto hover:brightness-105 active:scale-95 transition disabled:opacity-50 cursor-pointer"
              >
                {loadingState ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
                <span>{loadingState ? 'Modeling Persona...' : 'Generate with AI'}</span>
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {/* Profile Card */}
              <div className="md:col-span-1 p-6 rounded-2xl bg-white border border-slate-100 shadow-sm flex flex-col items-center text-center space-y-4">
                <div className="w-20 h-20 rounded-full bg-pink-100 flex items-center justify-center text-3xl shadow-inner border border-pink-200">
                  👤
                </div>
                <div>
                  <h3 className="text-lg font-black text-slate-850">{personaData.name}</h3>
                  <span className="px-2 py-0.5 bg-pink-55 border border-pink-100 text-pink-700 font-extrabold text-[9px] uppercase tracking-wider rounded-full">Target Persona</span>
                </div>
                <div className="w-full space-y-2.5 pt-4 text-xs font-bold text-slate-650 border-t border-slate-50 text-left">
                  <div className="flex justify-between"><span>Age Range:</span><span className="text-slate-800">{personaData.age}</span></div>
                  <div className="flex justify-between"><span>Gender Group:</span><span className="text-slate-800">{personaData.gender}</span></div>
                  <div className="flex justify-between"><span>Income Bracket:</span><span className="text-slate-800">{personaData.income}</span></div>
                </div>
              </div>

              {/* Persona Details Card */}
              <div className="md:col-span-2 space-y-6">
                <div className="p-6 rounded-2xl bg-white border border-slate-100 shadow-sm grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div>
                    <h4 className="text-xs font-black text-slate-800 uppercase tracking-widest mb-3 border-b border-slate-50 pb-1">Interests</h4>
                    <div className="flex flex-wrap gap-1.5">
                      {(personaData.interests || []).map((t, i) => (
                        <span key={i} className="px-2.5 py-1 bg-violet-50 text-violet-650 font-bold text-[10px] rounded-lg border border-violet-100/50">{t}</span>
                      ))}
                    </div>
                  </div>
                  <div>
                    <h4 className="text-xs font-black text-slate-800 uppercase tracking-widest mb-3 border-b border-slate-50 pb-1">Goals</h4>
                    <ul className="text-xs text-slate-550 space-y-1.5 font-semibold list-disc list-inside">
                      {(personaData.goals || []).map((t, i) => <li key={i}>{t}</li>)}
                    </ul>
                  </div>
                </div>

                <div className="p-6 rounded-2xl bg-white border border-slate-100 shadow-sm space-y-4">
                  <h4 className="text-xs font-black text-slate-800 uppercase tracking-widest border-b border-slate-50 pb-1">Pain Points</h4>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {(personaData.pain_points || []).map((p, i) => (
                      <div key={i} className="p-3 bg-red-50/10 border border-red-100/40 rounded-xl text-xs font-semibold text-slate-650">
                        {p}
                      </div>
                    ))}
                  </div>
                </div>

                <div className="p-6 rounded-2xl bg-white border border-slate-100 shadow-sm">
                  <h4 className="text-xs font-black text-slate-800 uppercase tracking-widest border-b border-slate-50 pb-1.5 mb-3">Buying Behavior</h4>
                  <p className="text-xs text-slate-550 font-semibold leading-relaxed">{personaData.buying_behavior}</p>
                </div>
              </div>
            </div>
          )}
        </motion.div>
      )}

      {activeTab === 'icp' && (
        <motion.div variants={item} className="space-y-6">
          {!icpData ? (
            <div className="rounded-2xl p-8 bg-white border border-slate-100 shadow-sm text-center space-y-4">
              <div className="w-12 h-12 bg-blue-50 text-blue-500 rounded-full flex items-center justify-center mx-auto shadow-inner">
                <Building className="w-6 h-6" />
              </div>
              <h3 className="text-base font-extrabold text-slate-850">Generate Ideal Customer Profile</h3>
              <p className="text-xs text-slate-400 font-semibold max-w-md mx-auto">Analyze startup structures to generate target industry, company scale, budget allocations, and key stakeholders.</p>
              <button
                onClick={generateICP}
                disabled={loadingState}
                className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-violet-600 to-pink-500 text-white text-xs font-black shadow-md flex items-center gap-1.5 mx-auto hover:brightness-105 active:scale-95 transition disabled:opacity-50 cursor-pointer"
              >
                {loadingState ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
                <span>{loadingState ? 'Mapping ICP Profile...' : 'Generate with AI'}</span>
              </button>
            </div>
          ) : (
            <div className="p-6 rounded-2xl bg-white border border-slate-100 shadow-sm space-y-6">
              <h3 className="text-base font-extrabold text-slate-850 border-b border-slate-50 pb-2 flex items-center gap-1.5">
                <Building className="w-5 h-5 text-blue-500" />
                <span>Ideal Customer Profile (ICP)</span>
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs font-bold text-slate-650">
                <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl space-y-1">
                  <span className="text-[10px] text-slate-400 uppercase tracking-wider block">Target Industry / Sector</span>
                  <span className="text-slate-800 font-black text-sm">{icpData.industry}</span>
                </div>
                <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl space-y-1">
                  <span className="text-[10px] text-slate-400 uppercase tracking-wider block">Company Size Scale</span>
                  <span className="text-slate-800 font-black text-sm">{icpData.company_size}</span>
                </div>
                <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl space-y-1">
                  <span className="text-[10px] text-slate-400 uppercase tracking-wider block">Target Budget Size</span>
                  <span className="text-slate-800 font-black text-sm">{icpData.budget}</span>
                </div>
                <div className="p-4 bg-slate-50 border border-slate-100 rounded-xl space-y-1">
                  <span className="text-[10px] text-slate-400 uppercase tracking-wider block">Target Geography</span>
                  <span className="text-slate-800 font-black text-sm">{icpData.geography}</span>
                </div>
              </div>

              <div className="p-4 bg-violet-50/20 border border-violet-100/50 rounded-xl">
                <h4 className="text-xs font-black text-slate-800 uppercase tracking-widest mb-2.5">Key Decision Makers</h4>
                <div className="flex flex-wrap gap-2">
                  {(icpData.decision_makers || []).map((m, i) => (
                    <span key={i} className="px-3 py-1.5 bg-violet-55 border border-violet-100 text-violet-750 font-extrabold text-[10px] rounded-lg">{m}</span>
                  ))}
                </div>
              </div>
            </div>
          )}
        </motion.div>
      )}

      {activeTab === 'interview' && (
        <motion.div variants={item} className="space-y-6">
          {!interviewData ? (
            <div className="rounded-2xl p-8 bg-white border border-slate-100 shadow-sm text-center space-y-4">
              <div className="w-12 h-12 bg-amber-50 text-amber-500 rounded-full flex items-center justify-center mx-auto shadow-inner">
                <HelpCircle className="w-6 h-6" />
              </div>
              <h3 className="text-base font-extrabold text-slate-850">Generate Interview Guides</h3>
              <p className="text-xs text-slate-400 font-semibold max-w-md mx-auto">Create strategic validation questions, feedback forms, and customer survey guidelines automatically using AI.</p>
              <button
                onClick={generateInterviewGuide}
                disabled={loadingState}
                className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-violet-600 to-pink-500 text-white text-xs font-black shadow-md flex items-center gap-1.5 mx-auto hover:brightness-105 active:scale-95 transition disabled:opacity-50 cursor-pointer"
              >
                {loadingState ? <Loader2 className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}
                <span>{loadingState ? 'Drafting Guides...' : 'Generate with AI'}</span>
              </button>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left">
              {/* Validation Questions */}
              <div className="p-6 bg-white border border-slate-100 rounded-2xl shadow-sm space-y-4">
                <h4 className="text-sm font-extrabold text-slate-850 flex items-center gap-1.5 border-b border-slate-50 pb-2">
                  <span className="w-2 h-2 bg-indigo-500 rounded-full" />
                  <span>Validation Questions</span>
                </h4>
                <ul className="space-y-3">
                  {(interviewData.validation_questions || []).map((q, i) => (
                    <li key={i} className="p-3 bg-indigo-50/10 border border-indigo-100/30 rounded-xl text-xs font-semibold text-slate-650 leading-relaxed">
                      {q}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Survey Questions */}
              <div className="p-6 bg-white border border-slate-100 rounded-2xl shadow-sm space-y-4">
                <h4 className="text-sm font-extrabold text-slate-850 flex items-center gap-1.5 border-b border-slate-50 pb-2">
                  <span className="w-2 h-2 bg-pink-500 rounded-full" />
                  <span>Survey Forms</span>
                </h4>
                <ul className="space-y-3">
                  {(interviewData.survey_questions || []).map((q, i) => (
                    <li key={i} className="p-3 bg-pink-50/10 border border-pink-100/30 rounded-xl text-xs font-semibold text-slate-650 leading-relaxed">
                      {q}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Interview Questions */}
              <div className="p-6 bg-white border border-slate-100 rounded-2xl shadow-sm space-y-4">
                <h4 className="text-sm font-extrabold text-slate-850 flex items-center gap-1.5 border-b border-slate-50 pb-2">
                  <span className="w-2 h-2 bg-amber-500 rounded-full" />
                  <span>User Interviews</span>
                </h4>
                <ul className="space-y-3">
                  {(interviewData.interview_questions || []).map((q, i) => (
                    <li key={i} className="p-3 bg-amber-50/10 border border-amber-100/30 rounded-xl text-xs font-semibold text-slate-650 leading-relaxed">
                      {q}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </motion.div>
      )}

    </motion.div>
  );
}
