const officegen = require('officegen');
const fs = require('fs');
const path = require('path');

function generatePptx(data, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const dir = path.dirname(outputPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      const pptx = officegen('pptx');
      pptx.setDocTitle(data.idea || 'Startup Pitch');

      // Title Slide
      pptx.makeTitleSlide(
        data.idea || 'Startup Pitch',
        'AI Startup Pitch Deck\nGenerated by StartupForge AI Co-Founder'
      );

      const slides = data.pitch?.slides || [
        { title: 'Problem', content: 'The problem your startup solves' },
        { title: 'Solution', content: 'Your unique value proposition' },
        { title: 'Market', content: 'TAM/SAM/SOM analysis' },
        { title: 'Business Model', content: 'Revenue streams and pricing' },
        { title: 'Competition', content: 'Competitive landscape' },
        { title: 'Financials', content: 'Revenue projections' },
        { title: 'Ask', content: 'Funding requirements' },
      ];

      for (const s of slides) {
        const slide = pptx.makeNewSlide();
        
        // Slide Title
        slide.addText(s.title, {
          y: 50,
          x: 50,
          font_size: 24,
          font_face: 'Arial',
          color: '4F46E5',
          bold: true,
        });

        // Slide Content
        slide.addText(s.content, {
          y: 120,
          x: 50,
          font_size: 14,
          font_face: 'Arial',
          color: '334155',
        });
      }

      const out = fs.createWriteStream(outputPath);
      pptx.generate(out);

      out.on('close', () => resolve(outputPath));
      out.on('error', (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generatePptx };
