# pyright: reportAttributeAccessIssue=false
from pptx import Presentation
from pptx.util import Inches

def generate_pptx(data: dict, output_path: str) -> str:
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    
    # 1. Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_shape = slide.shapes.title
    subtitle_shape = slide.placeholders[1] if len(slide.placeholders) > 1 else None
    if title_shape is not None:
        title_shape.text = data.get("idea", "Startup Idea")
    if subtitle_shape is not None:
        subtitle_shape.text = "AI Startup Pitch Deck\nGenerated by AI Startup Co-Founder"

    # 2. Add slides dynamically from Pitch Agent
    slides = data.get("pitch", {}).get("slides", [])
    if not slides:
        # Fallback to general slides if none produced
        slides = [
            {"title": "Problem", "content": "The problem your startup solves"},
            {"title": "Solution", "content": "Your unique value proposition"},
            {"title": "Market", "content": "TAM/SAM/SOM analysis"},
            {"title": "Business Model", "content": "Revenue streams and pricing"},
            {"title": "Competition", "content": "Competitive landscape"},
            {"title": "Financials", "content": "Revenue projections"},
            {"title": "Ask", "content": "Funding requirements"}
        ]

    for slide_info in slides:
        title = slide_info.get("title", "")
        content = slide_info.get("content", "")
        
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        title_shape = slide.shapes.title
        if title_shape is not None:
            title_shape.text = title
            
        if len(slide.placeholders) > 1:
            body = slide.placeholders[1]
            tf = body.text_frame
            tf.text = ""
            
            p = tf.paragraphs[0]
            p.text = content
            
            # Enrich specific slides based on their title keyword
            title_lower = title.lower()
            if "business model" in title_lower:
                streams = data.get("business_model", {}).get("revenue_streams", [])
                if streams:
                    p = tf.add_paragraph()
                    p.text = "\nKey Revenue Streams:"
                    p.level = 0
                    p.font.bold = True
                    for stream in streams:
                        p = tf.add_paragraph()
                        p.text = f"• {stream}"
                        p.level = 1
            elif "financial" in title_lower or "revenue" in title_lower or "forecast" in title_lower:
                projections = data.get("revenue", {}).get("projections", [])
                if projections:
                    p = tf.add_paragraph()
                    p.text = "\n5-Year Financial Projections:"
                    p.level = 0
                    p.font.bold = True
                    for proj in projections:
                        year = proj.get("year", "")
                        rev = proj.get("revenue", 0)
                        users = proj.get("users", 0)
                        p = tf.add_paragraph()
                        p.text = f"• {year}: ${rev}M Revenue, {users:,} Users"
                        p.level = 1
            elif "compet" in title_lower or "rival" in title_lower:
                competitors = data.get("competitors", {}).get("competitors", [])
                if competitors:
                    p = tf.add_paragraph()
                    p.text = "\nCompetitive Landscape:"
                    p.level = 0
                    p.font.bold = True
                    for comp in competitors:
                        comp_name = comp.get("name", "")
                        share = comp.get("market_share", "")
                        adv = comp.get("competitive_advantage", "")
                        p = tf.add_paragraph()
                        p.text = f"• {comp_name} ({share} share): {adv}"
                        p.level = 1
            elif "market" in title_lower:
                m_size = data.get("market", {}).get("market_size", {})
                if m_size:
                    p = tf.add_paragraph()
                    p.text = "\nMarket Sizing:"
                    p.level = 0
                    p.font.bold = True
                    for size_type in ["tam", "sam", "som"]:
                        if size_type in m_size:
                            p = tf.add_paragraph()
                            p.text = f"• {size_type.upper()}: {m_size[size_type]}"
                            p.level = 1
    prs.save(output_path)
    return output_path
